[workspace]
resolver = "2"
members = [
  "crates/api",
  "crates/player",
  "crates/tui",
  "crates/data",
  "crates/error",
  "crates/player",
  "crates/testing",
  "crates/gytm",
  "crates/state",
]

[workspace.dependencies]
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "cookies",
  "native-tls",
] }
ratatui = "0.30"
crossterm = "0.29.0"
dirs = "6.0.0"
thiserror = "2.0.18"
sha1 = "0.11.0"
rand = "0.10"
chrono = "0.4.44"
tempfile = "3"
libsqlite3-sys = { version = "*", features = ["bundled"] }
rookie = { version = "0.5.6" }
url = "2.5.8"
rusqlite = { version = "0.31.0", features = ["bundled"] }

player = { path = "crates/player" }
tui = { path = "crates/tui" }
api = { path = "crates/api" }
data = { path = "crates/data" }
error = { path = "crates/error" }
gytm = { path = "crates/gytm" }
state = { path = "crates/state" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
